shell: thefuck handler

diff --git a/shell/shell_functions b/shell/shell_functions
--- a/shell/shell_functions
+++ b/shell/shell_functions
@@ -160,3 +160,20 @@ function vmbymac() {
   mac="$(tr '[:upper:]' '[:lower:]' <<<"$1")"
   govc object.collect -json -type m / config.hardware.device | jq -r '. | select(.ChangeSet[].Val.VirtualDevice[].MacAddress == "'"$mac"'") | [.Obj.Type, .Obj.Value] | join(":")' | xargs govc ls -L
 }
+
+# thefuck with command not found handler
+if command -v thefuck; then
+  eval $(thefuck --alias)
+  command_not_found_handler() {
+    TF_SHELL_ALIASES="$(alias)"
+    TF_CMD="$(
+      export TF_SHELL_ALIASES;
+      export TF_SHELL=zsh;
+      export TF_HISTORY="$@";
+      export PYTHONIOENCODING=utf-8;
+      thefuck THEFUCK_ARGUMENT_PLACEHOLER
+    )" && eval "$TF_CMD"
+
+    (test -n "$TF_CMD" && print -s "$TF_CMD") || echo "$0: command not found"
+  }
+fi
